server:
  port: 0

spring:
  application:
    name: tickets-api



eureka:
 instance:
   preferIpAddress: true
 client:
   fetchRegistry: true
   registerWithEureka: true
   serviceUrl:
    defaultZone: http://localhost:8761/eureka